[package]
name = "boardbuilder-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
image = "0.24.5"
ril = { version = "0.9.0", features = ["all-pure"] }
thiserror = "1.0.38"
